# Generated by Django 3.2.9 on 2022-05-17 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
        ('publications', '0001_initial'),
        ('people', '0001_initial'),
        ('projects', '0002_remove_pategory_title_sk'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.pategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='people.person'),
        ),
        migrations.AddField(
            model_name='project',
            name='related_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.publication'),
        ),
        migrations.AddField(
            model_name='project',
            name='related_research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.research'),
        ),
    ]
