# Generated by Django 3.2.9 on 2022-03-17 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220317_0156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
