# Generated by Django 3.2.9 on 2022-05-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_pategory_title_sk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pategory',
            name='title_sk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
