# Generated by Django 3.2.9 on 2022-03-17 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
