# Generated by Django 3.2.9 on 2022-04-30 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_person_status'),
        ('projects', '0010_auto_20220430_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='Project_title',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default='uncategorized', on_delete=django.db.models.deletion.CASCADE, to='people.person'),
        ),
    ]
