# Generated by Django 3.2.9 on 2022-04-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20220430_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Project_title',
            new_name='title',
        ),
    ]
