# Generated by Django 3.2.9 on 2022-04-30 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_project_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_by',
            new_name='category',
        ),
    ]
