# Generated by Django 3.2.9 on 2022-04-30 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_created_by'),
        ('projects', '0025_alter_project_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='related_publication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publications.publication'),
        ),
    ]
