# Generated by Django 3.2.9 on 2022-04-30 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_alter_research_created_by'),
        ('projects', '0026_project_related_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='related_research',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='research.research'),
        ),
    ]
