# Generated by Django 3.2.9 on 2022-05-01 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_project_related_research'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='related_publication',
        ),
        migrations.RemoveField(
            model_name='project',
            name='related_research',
        ),
    ]
