# Generated by Django 3.2.9 on 2022-05-01 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_research_related_project'),
        ('publications', '0010_auto_20220501_0223'),
        ('projects', '0028_auto_20220501_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='related_publication',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.publication'),
        ),
        migrations.AddField(
            model_name='project',
            name='related_research',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='research.research'),
        ),
    ]
