# Generated by Django 3.2.9 on 2022-05-01 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20220501_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.category'),
        ),
    ]
