# Generated by Django 3.2.9 on 2022-05-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_auto_20220501_0223'),
        ('projects', '0032_auto_20220501_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='related_publication',
        ),
        migrations.AddField(
            model_name='project',
            name='related_publication',
            field=models.ManyToManyField(related_name='publication', to='publications.Publication'),
        ),
    ]
