# Generated by Django 3.2.9 on 2022-05-01 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_auto_20220501_0223'),
        ('projects', '0035_alter_project_related_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='related_publication',
        ),
        migrations.AddField(
            model_name='project',
            name='related_publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.publication'),
        ),
    ]
