# Generated by Django 3.2.9 on 2022-05-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_research_related_project'),
        ('projects', '0036_auto_20220501_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='related_research',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='research.research'),
        ),
    ]
