# Generated by Django 3.2.9 on 2022-05-17 08:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0041_auto_20220516_0828'),

    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Pategory',
        ),
    ]
