# Generated by Django 3.2.9 on 2022-05-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_rename_category_pategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='related_publication',
        ),
        migrations.RemoveField(
            model_name='project',
            name='related_research',
        ),
    ]
