# Generated by Django 3.2.9 on 2022-05-24 23:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='body',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
