# Generated by Django 3.2.9 on 2022-05-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_alter_research_created_by'),
        ('publications', '0003_alter_publication_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='related_research',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='research.research'),
        ),
    ]
