# Generated by Django 3.2.9 on 2022-05-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20220525_0137'),
        ('projects', '0006_auto_20220525_0135'),
        ('publications', '0004_auto_20220525_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='related_project',
        ),
        migrations.AddField(
            model_name='publication',
            name='related_project',
            field=models.ManyToManyField(to='projects.Project'),
        ),
        migrations.RemoveField(
            model_name='publication',
            name='related_research',
        ),
        migrations.AddField(
            model_name='publication',
            name='related_research',
            field=models.ManyToManyField(to='research.Research'),
        ),
    ]
