# Generated by Django 3.2.9 on 2022-05-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20220525_0310'),
        ('projects', '0008_alter_project_created_by'),
        ('people', '0004_auto_20220525_0208'),
        ('publications', '0006_auto_20220525_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='created_by',
            field=models.ManyToManyField(blank=True, to='people.Person'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='related_project',
            field=models.ManyToManyField(blank=True, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='related_research',
            field=models.ManyToManyField(blank=True, to='research.Research'),
        ),
    ]
