# Generated by Django 3.2.9 on 2022-05-01 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_remove_publication_related_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='related_research',
        ),
    ]
