# Generated by Django 3.2.9 on 2022-05-01 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_alter_research_created_by'),
        ('projects', '0028_auto_20220501_0211'),
        ('publications', '0009_alter_publication_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='publication',
            name='related_research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.research'),
        ),
    ]
