# Generated by Django 3.2.9 on 2022-05-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_person_status'),
        ('publications', '0010_auto_20220501_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='created_by',
        ),
        migrations.AddField(
            model_name='publication',
            name='created_by',
            field=models.ManyToManyField(to='people.Person'),
        ),
    ]
