# Generated by Django 3.2.9 on 2022-05-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_auto_20220512_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='related_project',
        ),
    ]
