# Generated by Django 3.2.9 on 2022-05-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20220514_2117'),
        ('publications', '0011_auto_20220512_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='created_by',
        ),
        migrations.AddField(
            model_name='publication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.person'),
        ),
    ]
