# Generated by Django 3.2.9 on 2022-05-17 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220517_1643'),
        ('people', '0001_initial'),
        ('publications', '0002_auto_20220517_1643'),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='people.person'),
        ),
        migrations.AddField(
            model_name='research',
            name='related_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='research',
            name='related_publication',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.publication'),
        ),
    ]
