# Generated by Django 3.2.9 on 2022-05-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20220525_0208'),
        ('research', '0003_auto_20220525_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='created_by',
        ),
        migrations.AddField(
            model_name='research',
            name='created_by',
            field=models.ManyToManyField(blank=True, null=True, to='people.Person'),
        ),
    ]
