# Generated by Django 3.2.9 on 2022-05-25 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20220525_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='related_project',
        ),
        migrations.RemoveField(
            model_name='research',
            name='related_publication',
        ),
    ]
