# Generated by Django 3.2.9 on 2022-05-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20220525_0208'),
        ('research', '0005_auto_20220525_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='created_by',
            field=models.ManyToManyField(blank=True, to='people.Person'),
        ),
    ]
