# Generated by Django 3.2.9 on 2022-05-01 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20220501_0211'),
        ('research', '0006_research_related_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='related_project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
