# Generated by Django 3.2.9 on 2022-05-15 14:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20220514_2117'),
        ('research', '0008_auto_20220514_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='related_project',
        ),
        migrations.RemoveField(
            model_name='research',
            name='related_publication',
        ),
        migrations.AlterField(
            model_name='research',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='research',
            name='created_by',
        ),
        migrations.AddField(
            model_name='research',
            name='created_by',
            field=models.ManyToManyField(to='people.Person'),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
