# Generated by Django 3.2.9 on 2022-05-15 15:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_auto_20220514_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='research',
            name='related_project',
        ),
        migrations.RemoveField(
            model_name='research',
            name='related_publication',
        ),
        migrations.AlterField(
            model_name='research',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(default=' ', max_length=255, null=True),
        ),
    ]
