# Generated by Django 3.2.9 on 2022-05-16 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_auto_20220516_0828'),
        ('publications', '0011_auto_20220512_1126'),
        ('research', '0008_auto_20220514_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='related_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='research',
            name='related_publication',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.publication'),
        ),
    ]
