# Generated by Django 3.2.9 on 2022-05-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_auto_20220515_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='created_by',
        ),
    ]
