# Generated by Django 3.2.9 on 2022-05-17 14:20

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_sk', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Employee', 'Employee'), ('Student', 'Student'), ('Doctorand', 'Doctorand'), ('Uncategorized', 'Uncategorized')], max_length=256)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('body_sk', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
