# Generated by Django 3.2.9 on 2022-03-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
