# Generated by Django 3.2.9 on 2022-05-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20220525_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='title_sk',
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(blank=True, default='../static/profilePic.png', null=True, upload_to=''),
        ),
    ]
