# Generated by Django 3.2.9 on 2022-03-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20220330_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Student', 'Student'), ('Doctorand', 'Doctorand')], max_length=256),
        ),
    ]
