# Generated by Django 3.2.9 on 2022-05-18 08:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0002_indexcontent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='IndexPost',
        ),
    ]
