# Generated by Django 3.2.9 on 2022-05-18 08:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0003_rename_post_indexpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexPost',
            new_name='Post',
        ),
    ]
