# Generated by Django 3.2.9 on 2022-05-24 23:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_rename_indexcontent_indexstaticcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tmp',
            field=ckeditor.fields.RichTextField(blank=True, editable=False, null=True),
        ),
    ]
