# Generated by Django 3.2.9 on 2022-04-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_post_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test',
        ),
    ]
